### ISSUE TITLE
Cut alpha release

### ISSUE THREAD

**Issue by adigitoleo** [seismic-anisotropy/PyDRex#185]
What needs to be done:
- [x] `git tag -a v0.0.1`
- [x] Add `build` and `twine` packages as dev dependencies
- [x] Remove spaces around `>=` in line 5 of `pyproject.toml`
- [x] Create account on test.pypi.org
- [x] Make sure `python -m build` works
- [x] Make sure all the auxiliary/data files are present in the `dist/*.gz`
- [x] Upload to test index: `python -m twine upload --repository testpypi dist/*`
- [x] Try to install it: `python -m pip install --index-url https://test.pypi.org/simple/ --no-deps pydrex` ([why `--no-deps`?](https://packaging.python.org/en/latest/tutorials/packaging-projects/#installing-your-newly-uploaded-package))
- [x] Register an account on https://pypi.org
- [x] `python -m twine upload dist/*`
- [x] Try installing `python -m pip install pydrex`
- [ ] Mint a DOI for the version with zenodo? DOI is nice for academic citation workflow. Use https://sandbox.zenodo.org/ to test. Looks like it might require [cutting actual github releases](https://coderefinery.github.io/github-without-command-line/doi/#step-3-create-a-release-and-get-a-doi) which is an unfortunate thing (why are annotated git tags not enough? Github already allows downloading source archives for a tag...)
- ~~If we do end up cutting "releases" in addition to tags, we should automate that based on annotated tags on `main` in another `.github/` workflow.~~

**Comment by adigitoleo** [comment]
https://test.pypi.org/project/pydrex/0.0.1rc1/

**Comment by adigitoleo** [comment]
Using git tags instead of releases is a decade-old feature request in zenodo: https://github.com/zenodo/zenodo/issues/40

Automatic tags -> releases would rely on one of several unofficial GH actions, doesn't look so appealing after all. Can do it manually [using the gh command line](https://cli.github.com/manual/gh_release_create) after making the git tag.

**Comment by Patol75** [comment]
How is this one coming along? It is really exciting to think that PyDRex will be on PyPI. Well done!

**Comment by adigitoleo** [comment]
https://pypi.org/project/pydrex/0.0.1/

Should add a github release + zenodo once #186 is merged. Yeah, forgot to update the README installation instructions but that's too bad, can do it for the next patch release which introduces the deformation mechanism selector.

Github release should probably use the new `CHANGELOG.md` file as an "asset".
