### ISSUE TITLE
remove vtk dependency entirely in favour of meshio

### ISSUE THREAD

**Issue by adigitoleo** [seismic-anisotropy/PyDRex#86]
The [meshio](https://github.com/nschloe/meshio) package handles VTK grids and many others. It is probably better to use that to replace `vtk_helpers.py`. Meshio can also be used to read interpolation grids for steady flow simulations.

Another reason to avoid the vtk dependency is the issue of vtk version conflicts which I have seen before when trying to import vtk in the Fluidity pythonb interface. Fluidity or another FEM code will usually depend on VTK and load VTK symbols which may not be the same as those requested by the PyPI vtk module.

**Comment by adigitoleo** [comment]
vtk dep removed in #139

**Comment by Patol75** [comment]
Is there still a reason to include `meshio`?

**Comment by adigitoleo** [comment]
> Is there still a reason to include `meshio`

At the moment it's not used because I removed the VTK readers, but maybe it's worth having some methods to read e.g. Fluidity meshes using meshio, or I guess we can have users do that on their own and not include it here.

**Comment by Patol75** [comment]
I would say let's close for now and potentially reopen if the need for it arises.
